### PR TITLE
Plugin updates

### PR DESCRIPTION
**Pull request by cossssmin**
## Breaking

- requires Node >=12

## Added

- GitHub Actions CI workflow
- xo for linting
- Dependabot

## Changed

- using c8 instead of nyc
- updated tests
- renamed license file
- updated readme

## Removed

- removed Travis CI worflow

### CODE REVIEW

**Comment by cossssmin** [comment]
@Scrum can you please give me write permissions on this one as well, so I don't need to maintain a separate fork? Thanks!

**Comment by cossssmin** [comment]
I've started this because I initially needed to report an issue with the plugin not working on elements that contain HTML nodes, but couldn't write a test to prove it because I simply couldn't get the test suite working locally. It's a needed update anyway, many packages were extremely outdated.

Once this is merged I'll write a failing test for my initial issue and we can take it from there 👍

P.S.: please don't merge the other dependabot PRs before this, some are already done in this PR and the rest we can take care after. Thanks!

**Comment by cossssmin** [comment]
@Scrum think we both forgot about this one :) Can you please give me the permissions so I can merge? Thanks!

**Comment by cossssmin** [comment]
@Scrum ping :)

**Comment by Scrum** [comment]
> @Scrum ping :)

sorry

**Pull request merged**
